### ISSUE TITLE
Plans for Auto Restart?

### ISSUE THREAD

**Issue by xMathayus** [AriesLR/ALR-Palworld-Resources#1]
Are there any plans for an auto restart and Rcon integration to broadcast the restart message?

**Comment by AriesLR** [comment]
I still do have plans for that since people seem to be using this, I personally switched to [WindowsGSM](https://windowsgsm.com) with the Palworld plugin, but there are still a few issues I'm having with WindowsGSM, mainly the backups save more than needed, but also rcon integration doesn't exist. WindowsGSM does have discord alerts and a lot of other useful features though. I'm unsure of if I can even manage rcon integration within a batch file, but I can try. 

I don't have plans to abandon this project, but I am working on a lighter weight version meant to work with WindowsGSM since it's lacking some features I'd like to have. Since they're based on the same thing though I can work on both at the same time.

**Comment by AriesLR** [comment]
### Never fear, restarts are here! 

This project (ALR-Palworld-Resources/PDSB/PDSL) are now unsupported as I'm remaking it from the ground up. 

You'll find an auto restart feature and more with [PalHub](https://github.com/AriesLR/PalHub), the successor to PDSL/PDSB.

If you're still using this, I recommend switching to [PalHub](https://github.com/AriesLR/PalHub) as I will continue to support it for some time as I'm actively developing it.
