### ISSUE TITLE
Cannot find path C:\Program Files

### ISSUE THREAD

**Issue by jdborden23** [AriesLR/ALR-Palworld-Resources#3]
I have all the configuration done and have been using this tool for a while. It has been giving me output after enabling automatic backups like so:
WARNING: The system cannot find the file specified.
C:\Program

WARNING: The system cannot find the file specified.
Files

WARNING: The system cannot find the file specified.
(x86)

The backups folder I specified for saves and configs is writing zip archives, but they are completely empty each time. I tried changing the path (assuming the spaces were the issue) to %ProgramFiles(x86)% and other fixes but still having the same issue. Am I supposed to set this up differently somehow?

My palworld server is installed under C:\Program Files(x86)\Steam\steamapps\common

**Comment by AriesLR** [comment]
It's definitely the spaces, just woke up gonna eat quick and then I'll look into solving this for you. I appreciate you giving me all the information you could. 

Just to confirm though, you did have the file path within quotations, correct? The spaces typically wouldn't be an issue within quotes. For example `set ZIP_DIR="C:\Program Files\7-Zip\7z.exe"` should throw the same error as your server path

**Comment by AriesLR** [comment]
Correction to my previous comment, upon testing I think 7zip is what doesn't like the spaces. Continuing to look into this.

**Comment by AriesLR** [comment]
Okay I'm about to post Release v1.2.1 that should solve your issue. You can keep your server directory as such: `set SERVER_DIR="C:\Program Files (x86)\Steam\steamapps\common\PalServer"`

As of right now at least you will need to keep your backup directory somewhere without spaces until I can figure out why powershell doesn't like the path being in a string. (Yes, it's a batch, but powershell handles the save purging since batch can only do days easily and powershell can do hours)

**Comment by jdborden23** [comment]
Ok awesome. Yes I am using quotes around the directory. When you post this release it will fix this issue so we can use server directory like you put above?

**Comment by AriesLR** [comment]
Release v1.2.1 is out, if you only want the backups, there is also the lighter weight "PDSB" that I released last night and just updated with the same fixes. Feel free to open another issue if you find anything else wrong. I tend to do most of this work when I'm exhausted so I definitely expect issues to arise from time to time due to my own human error.
